### ISSUE TITLE
Get an error message

### ISSUE THREAD

**Issue by mehmetze** [papplication/alice#2]
I get an this error messages;

[06/05/2019 01:56:00.490] [LOG]    Harvest started
[06/05/2019 01:56:00.494] [LOG]    Following cache: 4
[06/05/2019 01:56:00.498] [LOG]    Tags are:  funny gifs
[06/05/2019 01:56:00.502] [LOG]    Minimum note count: 32
[06/05/2019 01:56:00.505] [LOG]    ------------------------------
[06/05/2019 01:56:01.898] [LOG]    Follow blog: http://totallylaughed.tumblr.com
[06/05/2019 01:56:01.902] [LOG]    Post image: https://66.media.tumblr.com/57e5fc2bccebd1247d75986bdd67a153/tumblr_mt1tptSX4T1stnucso1_400.gif with tags: funny gifs,laugh out loud,michael cera,sexy,funny,gif,
[06/05/2019 01:56:01.912] [ERROR]  client.createPhotoPost: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (https.js:281:10)
    at Request.start (C:\Users\cimbo\OneDrive\Desktop\alice-master\src\node_modules\tumblr.js\node_modules\request\request.js:748:32)
    at Request.write (C:\Users\cimbo\OneDrive\Desktop\alice-master\src\node_modules\tumblr.js\node_modules\request\request.js:1498:10)
    at FormData.ondata (internal/streams/legacy.js:15:31)
    at FormData.emit (events.js:189:13)

**Comment by papplication** [comment]
I tried to reproduce the error but the exception did not come. _(Node.js v12.5.0 on macOS)_

> Post image: https://66.media.tumblr.com/57e5fc2bccebd1247d75986bdd67a153/tumblr_mt1tptSX4T1stnucso1_400.gif with tags: funny gifs,laugh out loud,michael cera,sexy,funny,gif,

Success.

**Have you experienced more similar errors?**
